<a href="https://colab.research.google.com/github/rpizarrog/Libro-Aprendizaje-Automatico.-Casos-de-Estudio-con-R-y-Python/blob/main/Python%20NoteBooks/Caso_regresi%C3%B3n_polinomial_m%C3%BAltiple_con_datos_de_rendimiento_acad%C3%A9mico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contexto de los datos

Este caso de estudio utiliza los datos que se cargaron en el caso de estudio anteriormente construido en R; los datos se relacionan con el rendimiento académico que tienen estudiantes relacionados con varias variables.

Es un conjunto de datos de aproximadamente 6000 registros con la siguiente estructura de datos:

•	*horas_estudio*: Número de horas que el estudiante dedica al estudio diario entre 1 a 10.
•	*tiempo_lectura*: Tiempo dedicado específicamente a la lectura académica entre 1 a 10.
•	*horas_sueno*: Cantidad de horas de sueño diario del estudiante entre 1-9.
•	*uso_redes*: Tiempo dedicado al uso de redes sociales, de 1-9.
•	*motivacion*: Nivel de motivación académica del estudiante 1-10.
•	*asistencia*: Porcentaje de asistencia a clase 60 a 100.
•	*nivel_socioeconomico*: Nivel socioeconómico del estudiante 1-5.
•	*apoyo_familiar*: Nivel de apoyo familiar percibido 1-10.
•	*estres*: Nivel de estrés académico 1-10.

• La variable dependiente es *rendimiento_academico* como un indicador que representa el desempeño académico global del estudiante en una escala: *70.00* a *100.00*.

Los datos se pueden encontrar en el servicio github.com siguiente: raw.githubusercontent.com/rpizarrog/Libro-Aprendizaje-Automatico.-Casos-de-Estudio-con-R-y-Python/refs/heads/main/datos/datos educacion para regresiones multiple polinomiales rendimiento_academico.csv .

El caso de estudio se puede recrean en el servicio *google collab*: https://colab.research.google.com/drive/1u_4oVVxfDOEv3A6avJs7rODqk2H49xkA?usp=sharing

De igual forma el documento *notebook* puede encontrarse en el servicio *github.com* en el espacio del autor:

# Objetivo

Crear, evaluar y comparar modelos de regresión múltiple con modelos polinomiales múltiples de segundo tercer orden y modelos *Lasso* y *Ridge*.

Se construye un modelo de regtresión múltiple y se valida el modelo para luego evaluarlo.

Posteriormente se construyen modelos polinomiales de segundo y tercer orden para ser comparado con el modelo de regresión múltiple original.

A la falta de validez en el postulado de multicolinealidad se cosntruyen modelos de regresión múltiple con datos normalizados y modelos regularizados *Lasso* y *Ridge* repectivamente.

Los modelos se aceptan si el valor de *r square ajustado* cumplen con el 85% o superior.

# Descripción

El caso de estudio sigue la misma metodología que ha sido incorporada en todos los casos anteriormente descritos y mencionada en el capítulo tres.

## Cargar librerías

Se cargan las librerías necesarias para la adecuada ejecución del caso de estudio.

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LassoCV
from sklearn.linear_model import RidgeCV
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import shapiro
from scipy.stats import kstest
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.stattools import durbin_watson
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import linear_reset
import statsmodels.api as sm

# Para validar posutalados
from statsmodels.stats.outliers_influence import (
    variance_inflation_factor
)
from statsmodels.stats.diagnostic import (
    het_breuschpagan,
    linear_reset
)
from statsmodels.stats.stattools import (
    durbin_watson
)
from scipy.stats import (
    shapiro
)

from scipy.stats import shapiro
from scipy.stats import kstest
from scipy.stats import anderson

from sklearn.linear_model import (
    LassoCV
)

from sklearn.linear_model import (
    RidgeCV
)

from sklearn.preprocessing import (
    PolynomialFeatures
)

## Cargar funciones

In [73]:
# Funciones para implementar y evaluar modelos de regresión múltiple en Python
# Se crean regresión regresión lineal mpultiple con datos originales
# Se crean modelos de regresi[]on polinomial múltiple con datos originales
# Se crean regresión lineal múltiple, Lasso y Ridge con datos normalizados
# Rubén Pizarro Gurrola
# Mayo 2026

#========================================================
# CARGAR DATOS
#========================================================

def f_cargar_datos(ruta_archivo):

    datos = pd.read_csv(ruta_archivo)

    return datos

#========================================================
# VISUALIZAR HEAD Y TAIL
#========================================================

def f_visualizar_head_tail_reducido(
        datos,
        n = 6
):

    #----------------------------------------------------
    # Total columnas
    #----------------------------------------------------

    total_columnas = datos.shape[1]

    #----------------------------------------------------
    # Primeras 4 columnas
    #----------------------------------------------------

    idx_prim = list(
        range(
            min(4, total_columnas)
        )
    )

    #----------------------------------------------------
    # Últimas 4 columnas
    #----------------------------------------------------

    idx_ult = list(
        range(
            max(total_columnas - 4, 0),
            total_columnas
        )
    )

    #----------------------------------------------------
    # Evitar duplicados
    #----------------------------------------------------

    idx_ult = [
        i for i in idx_ult
        if i not in idx_prim
    ]

    #----------------------------------------------------
    # Subconjuntos
    #----------------------------------------------------

    datos_prim = datos.iloc[:, idx_prim]

    datos_ult = datos.iloc[:, idx_ult]

    #----------------------------------------------------
    # HEAD
    #----------------------------------------------------

    head_prim = (
        datos_prim
        .head(n)
        .astype(str)
        .reset_index(drop = True)
    )

    head_ult = (
        datos_ult
        .head(n)
        .astype(str)
        .reset_index(drop = True)
    )

    #----------------------------------------------------
    # TAIL
    #----------------------------------------------------

    tail_prim = (
        datos_prim
        .tail(n)
        .astype(str)
        .reset_index(drop = True)
    )

    tail_ult = (
        datos_ult
        .tail(n)
        .astype(str)
        .reset_index(drop = True)
    )

    #----------------------------------------------------
    # Separadores
    #----------------------------------------------------

    sep_head = pd.DataFrame({
        "...": ["..."] * n
    })

    sep_tail = pd.DataFrame({
        "...": ["..."] * n
    })

    #----------------------------------------------------
    # Combinar HEAD
    #----------------------------------------------------

    head_comb = pd.concat(

        [
            head_prim,
            sep_head,
            head_ult
        ],

        axis = 1
    )

    #----------------------------------------------------
    # Combinar TAIL
    #----------------------------------------------------

    tail_comb = pd.concat(

        [
            tail_prim,
            sep_tail,
            tail_ult
        ],

        axis = 1
    )

    #----------------------------------------------------
    # Fila separadora
    #----------------------------------------------------

    fila_sep = pd.DataFrame(

        [["..."] * head_comb.shape[1]],

        columns = head_comb.columns
    )

    #----------------------------------------------------
    # Tabla final
    #----------------------------------------------------

    tabla = pd.concat(

        [
            head_comb,
            fila_sep,
            tail_comb
        ],

        ignore_index = True
    )

    return tabla

#========================================================
# DESCRIBIR DATOS
#========================================================

def f_describir_datos(datos):

    describe = datos.describe(include = 'all')

    structure = datos.dtypes

    return {
        "describe": describe,
        "structure": structure
    }

def f_convertir_dummis(datos, variable_dependiente):

    #----------------------------------------------------------
    # f_convertir_dummis()
    #
    # Objetivo:
    #   Convertir variables categóricas y booleanas
    #   a variables dummy, manteniendo la variable
    #   dependiente al final del DataFrame.
    #
    # Argumentos:
    #   datos                : DataFrame de pandas
    #   variable_dependiente : nombre de la variable objetivo
    #
    # Valor de retorno:
    #   DataFrame transformado
    #
    #----------------------------------------------------------

    #----------------------------------------------------------
    # Copiar datos
    #----------------------------------------------------------

    datos_dummis = datos.copy()


    #----------------------------------------------------------
    # Guardar variable dependiente
    #----------------------------------------------------------

    y = datos_dummis[variable_dependiente]


    #----------------------------------------------------------
    # Eliminar temporalmente variable dependiente
    #----------------------------------------------------------

    datos_dummis = datos_dummis.drop(
        columns = [variable_dependiente]
    )


    #----------------------------------------------------------
    # Detectar variables categóricas y booleanas
    #----------------------------------------------------------

    variables_convertir = datos_dummis.select_dtypes(
        include = ["object", "bool"]
    ).columns


    #----------------------------------------------------------
    # Convertir a variables dummy
    #----------------------------------------------------------

    datos_dummis = pd.get_dummies(
        datos_dummis,
        columns = variables_convertir,
        drop_first = True,
        dtype = int
    )


    #----------------------------------------------------------
    # Agregar variable dependiente al final
    #----------------------------------------------------------

    datos_dummis[variable_dependiente] = y


    #----------------------------------------------------------
    # Devolver resultado
    #----------------------------------------------------------

    return datos_dummis

#========================================================
# PARTICIONAR DATOS
#========================================================

def f_particionar_datos(datos,
                         proporcion_entrenamiento = 0.7):

    datos_entrenamiento, datos_validacion = train_test_split(
        datos,
        train_size = proporcion_entrenamiento,
        random_state = 2026
    )

    return {
        "datos_entrenamiento": datos_entrenamiento,
        "datos_validacion": datos_validacion
    }

#========================================================
# CONVERTIR FACTOR
#========================================================

def f_convertir_factor(datos):

    datos_mod = datos.copy()

    for col in datos_mod.columns:

        if datos_mod[col].dtype == 'object':

            datos_mod[col] = datos_mod[col].astype('category')

        if datos_mod[col].dtype == 'bool':

            datos_mod[col] = datos_mod[col].astype(int)

    return datos_mod

#========================================================
# REDONDEAR VARIABLES NUMÉRICAS
#========================================================

def f_redondear_numericas(datos,
                          decimales = 2):

    datos_out = datos.copy()

    columnas_num = datos_out.select_dtypes(include = np.number).columns

    datos_out[columnas_num] = datos_out[columnas_num].round(decimales)

    return datos_out

#========================================================
# MODELO REGRESIÓN LINEAL MÚLTIPLE
#========================================================

def f_construir_modelo_RLM(datos,
                           variable_dependiente,
                           ver_resumen = True):

    X = datos.drop(columns = [variable_dependiente])

    y = datos[variable_dependiente]

    X = pd.get_dummies(X,
                       drop_first = True)

    modelo = LinearRegression()

    modelo.fit(X, y)

    if ver_resumen:

        X_sm = sm.add_constant(X)

        modelo_sm = sm.OLS(y, X_sm).fit()

        print(modelo_sm.summary())

    return modelo

#========================================================
# MODELO REGRESIÓN LINEAL MÚLTIPLE
# CON STATSMODELS
#========================================================

def f_construir_modelo_RLM_statsmodels(

        datos,

        variable_dependiente,

        ver_resumen = True
):

    #----------------------------------------------------
    # Variables independientes
    #----------------------------------------------------

    X = datos.drop(

        columns = [variable_dependiente]
    )

    #----------------------------------------------------
    # Variable dependiente
    #----------------------------------------------------

    y = datos[variable_dependiente]

    #----------------------------------------------------
    # Copia directa
    # SIN VARIABLES DUMMY
    #----------------------------------------------------

    X = X.copy()

    #----------------------------------------------------
    # Constante
    #----------------------------------------------------

    X = sm.add_constant(

        X,

        has_constant = "add"
    )

    #----------------------------------------------------
    # Modelo OLS
    #----------------------------------------------------

    modelo = sm.OLS(

        y,

        X

    ).fit()

    #----------------------------------------------------
    # Resumen
    #----------------------------------------------------

    if ver_resumen:

        print(

            modelo.summary()
        )

    return modelo

#========================================================
# REGRESIÓN MÚLTIPLE POLINOMIAL
# CON STATSMODELS
#========================================================

from sklearn.preprocessing import (
    PolynomialFeatures
)

def f_multiple_polinomial(

        datos,

        variable_dependiente,

        grado = 2,

        ver_resumen = True

):

    #----------------------------------------------------
    # Variables independientes
    #----------------------------------------------------

    X = datos.drop(

        columns = [variable_dependiente]
    )

    #----------------------------------------------------
    # Variable dependiente
    #----------------------------------------------------

    y = datos[variable_dependiente]

    #----------------------------------------------------
    # Variables originales
    #----------------------------------------------------

    nombres_originales = X.columns

    #----------------------------------------------------
    # Transformación polinomial
    #----------------------------------------------------

    poly = PolynomialFeatures(

        degree = grado,

        include_bias = False
    )

    X_poly = poly.fit_transform(

        X
    )

    #----------------------------------------------------
    # Nombres variables polinomiales
    #----------------------------------------------------

    nombres_poly = poly.get_feature_names_out(

        nombres_originales
    )

    #----------------------------------------------------
    # DataFrame polinomial
    #----------------------------------------------------

    X_poly = pd.DataFrame(

        X_poly,

        columns = nombres_poly,

        index = X.index
    )

    #----------------------------------------------------
    # Constante
    #----------------------------------------------------

    X_poly = sm.add_constant(

        X_poly,

        has_constant = "add"
    )

    #----------------------------------------------------
    # Modelo OLS
    #----------------------------------------------------

    modelo = sm.OLS(

        y,

        X_poly

    ).fit()

    #----------------------------------------------------
    # Guardar estructura
    # IMPORTANTÍSIMO
    #----------------------------------------------------

    modelo.columnas_entrenamiento = X_poly.columns

    modelo.poly_transformador = poly

    modelo.nombres_originales = nombres_originales

    #----------------------------------------------------
    # Información
    #----------------------------------------------------

    print("\n============================")

    print(

        f"MODELO POLINOMIAL GRADO {grado}"
    )

    print("============================")

    print(

        f"Número de variables originales: "
        f"{len(nombres_originales)}"
    )

    print(

        f"Número de términos polinomiales: "
        f"{X_poly.shape[1]-1}"
    )

    #----------------------------------------------------
    # Resumen
    #----------------------------------------------------

    if ver_resumen:

        print(

            modelo.summary()
        )

    return modelo

#========================================================
# ESTANDARIZAR Y ESCALAR
#========================================================

def f_estandarizar_escalar(datos,
                           decimales = 4):

    datos_est = datos.copy()
    datos_esc = datos.copy()

    columnas_num = datos.select_dtypes(include = np.number).columns

    scaler_est = StandardScaler()

    scaler_minmax = MinMaxScaler()

    datos_est[columnas_num] = np.round(
        scaler_est.fit_transform(datos[columnas_num]),
        decimales
    )

    datos_esc[columnas_num] = np.round(
        scaler_minmax.fit_transform(datos[columnas_num]),
        decimales
    )

    return {
        "datos_estandarizados": datos_est,
        "datos_escalados": datos_esc
    }

#========================================================
# MODELO LASSO
#========================================================


def f_construir_modelo_lasso(

        datos,

        variable_dependiente,

        cv = 10,

        random_state = 2026,

        ver_resumen = True

):

    #----------------------------------------------------
    # Variables independientes
    #----------------------------------------------------

    X = datos.drop(

        columns = [variable_dependiente]
    )

    #----------------------------------------------------
    # Variable dependiente
    #----------------------------------------------------

    y = datos[variable_dependiente]

    #----------------------------------------------------
    # Modelo LASSO CV
    #----------------------------------------------------

    modelo = LassoCV(

        cv = cv,

        random_state = random_state

    )

    modelo.fit(

        X,

        y
    )

    #----------------------------------------------------
    # Coeficientes
    #----------------------------------------------------

    coeficientes = pd.DataFrame({

        "Variable":

            X.columns,

        "Coeficiente":

            np.round(
                modelo.coef_,
                4
            )
    })

    #----------------------------------------------------
    # Información
    #----------------------------------------------------

    if ver_resumen:

        print("\n============================")

        print("MODELO LASSO")

        print("============================")

        print(

            f"Lambda óptimo: "
            f"{round(modelo.alpha_,4)}"
        )

        print(

            f"Intercepto: "
            f"{round(modelo.intercept_,4)}"
        )

        print("\nCoeficientes:")

        print(coeficientes)

    #----------------------------------------------------
    # Guardar columnas
    #----------------------------------------------------

    modelo.columnas_entrenamiento = X.columns

    return modelo

  #========================================================
# MODELO RIDGE
#========================================================



def f_construir_modelo_ridge(
        datos,
        variable_dependiente,
        alphas = np.logspace(-4, 4, 100),
        cv = 10,
        ver_resumen = True
):

    #----------------------------------------------------
    # Variables independientes
    #----------------------------------------------------

    X = datos.drop(

        columns = [variable_dependiente]
    )

    #----------------------------------------------------
    # Variable dependiente
    #----------------------------------------------------

    y = datos[variable_dependiente]

    #----------------------------------------------------
    # Modelo RIDGE CV
    #----------------------------------------------------

    modelo = RidgeCV(

        alphas = alphas,

        cv = cv
    )

    modelo.fit(

        X,

        y
    )

    #----------------------------------------------------
    # Coeficientes
    #----------------------------------------------------

    coeficientes = pd.DataFrame({

        "Variable":

            X.columns,

        "Coeficiente":

            np.round(
                modelo.coef_,
                4
            )
    })

    #----------------------------------------------------
    # Información
    #----------------------------------------------------

    if ver_resumen:

        print("\n============================")

        print("MODELO RIDGE")

        print("============================")

        print(

            f"Lambda óptimo: "
            f"{round(modelo.alpha_,4)}"
        )

        print(

            f"Intercepto: "
            f"{round(modelo.intercept_,4)}"
        )

        print("\nCoeficientes:")

        print(coeficientes)

    #----------------------------------------------------
    # Guardar columnas entrenamiento
    #----------------------------------------------------

    modelo.columnas_entrenamiento = X.columns

    return modelo

#========================================================
# MULTICOLINEALIDAD VIF
#========================================================

def f_multicolinealidad(datos,
                        variable_dependiente):

    X = datos.drop(columns = [variable_dependiente])

    X = pd.get_dummies(X,
                       drop_first = True)

    X = sm.add_constant(X)

    vif = pd.DataFrame()

    vif["Variable"] = X.columns

    vif["VIF"] = [
        variance_inflation_factor(X.values, i)
        for i in range(X.shape[1])
    ]

    return vif

#========================================================
# DIAGNÓSTICO DE LINEALIDAD
#========================================================

def f_linealidad(modelo):

    #----------------------------------------------------
    # Valores ajustados
    #----------------------------------------------------

    ajustados = modelo.fittedvalues

    #----------------------------------------------------
    # Residuos
    #----------------------------------------------------

    residuos = modelo.resid

    #----------------------------------------------------
    # Gráfico
    #----------------------------------------------------

    plt.figure(

        figsize = (6,4)
    )

    plt.scatter(

        ajustados,

        residuos,

        color = "blue"
    )

    plt.axhline(

        0,

        linestyle = "--",

        color = "red"
    )

    plt.title(

        "Residuos vs Valores Ajustados"
    )

    plt.xlabel(

        "Valores ajustados"
    )

    plt.ylabel(

        "Residuos"
    )

    plt.show()

    #----------------------------------------------------
    # Interpretación
    #----------------------------------------------------

    print("\n============================")

    print("Diagnóstico de Linealidad")

    print("============================")

    print(
        "- Los residuos deben distribuirse "
        "aleatoriamente alrededor de 0."
    )

    print(
        "- No deben observarse patrones "
        "curvos."
    )

    print(
        "- Curvaturas sugieren "
        "no linealidad."
    )

#========================================================
# TEST DE LINEALIDAD
# RAMSEY RESET
#========================================================

def f_linealidad_test(

        modelo

):

    #----------------------------------------------------
    # Ramsey RESET
    #----------------------------------------------------

    resultado = linear_reset(

        modelo,

        power = 2,

        use_f = True
    )

    #----------------------------------------------------
    # Mostrar resultado
    #----------------------------------------------------

    print("\n============================")

    print("Test de Linealidad (Ramsey RESET)")

    print("============================")

    print(resultado)

    #----------------------------------------------------
    # Interpretación
    #----------------------------------------------------

    p_valor = resultado.pvalue

    print("\nInterpretación:")

    if p_valor > 0.05:

        print(
            "✔ No se rechaza H0 → "
            "El modelo es lineal "
            "(no hay evidencia de curvatura)"
        )

    else:

        print(
            "❌ Se rechaza H0 → "
            "Existe evidencia de no linealidad"
        )

    return resultado

#========================================================
# HOMOCEDASTICIDAD
#========================================================

def f_homocedasticidad(

        modelo

):

    #----------------------------------------------------
    # Residuos
    #----------------------------------------------------

    residuos = modelo.resid

    #----------------------------------------------------
    # Valores ajustados
    #----------------------------------------------------

    ajustados = modelo.fittedvalues

    #----------------------------------------------------
    # Matriz X usada en el modelo
    #----------------------------------------------------

    X = modelo.model.exog

    #----------------------------------------------------
    # Breusch-Pagan
    #----------------------------------------------------

    bp = het_breuschpagan(

        residuos,

        X
    )

    #----------------------------------------------------
    # Resultados
    #----------------------------------------------------

    resultado = pd.DataFrame({

        "Prueba": [

            "Breusch-Pagan"
        ],

        "LM Statistic": [

            round(bp[0], 4)
        ],

        "LM p-value": [

            round(bp[1], 4)
        ],

        "F Statistic": [

            round(bp[2], 4)
        ],

        "F p-value": [

            round(bp[3], 4)
        ]
    })

    #----------------------------------------------------
    # Gráfico
    #----------------------------------------------------

    plt.figure(

        figsize = (6,4)
    )

    plt.scatter(

        ajustados,

        residuos,

        color = "blue"
    )

    plt.axhline(

        0,

        linestyle = "--",

        color = "red"
    )

    plt.title(

        "Residuos vs Valores Ajustados"
    )

    plt.xlabel(

        "Valores ajustados"
    )

    plt.ylabel(

        "Residuos"
    )

    plt.show()

    #----------------------------------------------------
    # Interpretación
    #----------------------------------------------------

    print("\n============================")

    print("Diagnóstico de Homocedasticidad")

    print("============================")

    print(resultado)

    print("\nInterpretación:")

    if bp[1] > 0.05:

        print(
            "✔ No se rechaza H0 → "
            "Existe homocedasticidad"
        )

    else:

        print(
            "❌ Se rechaza H0 → "
            "Existe heterocedasticidad"
        )

    return resultado

#========================================================
# NORMALIDAD DE RESIDUOS
#========================================================

def f_normalidad(

        modelo

):

    #----------------------------------------------------
    # Residuos estandarizados
    #----------------------------------------------------

    residuos = modelo.resid

    residuos = (

        residuos - np.mean(residuos)

    ) / np.std(residuos)

    #----------------------------------------------------
    # SHAPIRO-WILK
    #----------------------------------------------------

    shapiro_test = shapiro(

        residuos
    )

    #----------------------------------------------------
    # KOLMOGOROV-SMIRNOV
    #----------------------------------------------------

    ks_test = kstest(

        residuos,

        'norm'
    )

    #----------------------------------------------------
    # ANDERSON-DARLING
    #----------------------------------------------------

    ad_test = anderson(

        residuos,

        dist = 'norm'
    )

    #----------------------------------------------------
    # Aproximación interpretación
    # scipy no devuelve p-value directo
    # usamos nivel 5%
    #----------------------------------------------------

    ad_critico_5 = ad_test.critical_values[2]

    ad_interpretacion = (

        "Normalidad"

        if ad_test.statistic < ad_critico_5

        else

        "No normalidad"
    )

    #----------------------------------------------------
    # RESULTADOS
    #----------------------------------------------------

    resultado = pd.DataFrame({

        "Prueba": [

            "Shapiro-Wilk",

            "Kolmogorov-Smirnov",

            "Anderson-Darling"
        ],

        "Estadistico": [

            round(shapiro_test.statistic, 4),

            round(ks_test.statistic, 4),

            round(ad_test.statistic, 4)
        ],

        "p_value": [

            round(shapiro_test.pvalue, 4),

            round(ks_test.pvalue, 4),

            np.nan
        ],

        "Interpretacion": [

            "Normalidad"

            if shapiro_test.pvalue > 0.05

            else

            "No normalidad",

            "Normalidad"

            if ks_test.pvalue > 0.05

            else

            "No normalidad",

            ad_interpretacion
        ]
    })

    #----------------------------------------------------
    # HISTOGRAMA
    #----------------------------------------------------

    plt.figure(

        figsize = (6,4)
    )

    plt.hist(

        residuos,

        bins = 15,

        density = True,

        alpha = 0.7
    )

    plt.title(

        "Histograma de residuos"
    )

    plt.xlabel(

        "Residuos estandarizados"
    )

    plt.ylabel(

        "Frecuencia"
    )

    plt.show()

    #----------------------------------------------------
    # QQ-PLOT
    #----------------------------------------------------

    sm.qqplot(

        residuos,

        line = '45'
    )

    plt.title(

        "QQ-Plot residuos"
    )

    plt.show()

    #----------------------------------------------------
    # RESULTADOS
    #----------------------------------------------------

    print("\n============================")

    print("Diagnóstico de Normalidad")

    print("============================")

    print(resultado)

    #----------------------------------------------------
    # Anderson detalle
    #----------------------------------------------------

    print("\nAnderson-Darling:")

    print(

        f"Estadístico = "
        f"{round(ad_test.statistic,4)}"
    )

    print(

        f"Valor crítico 5% = "
        f"{round(ad_critico_5,4)}"
    )

    print("\nInterpretación:")

    for i in range(len(resultado)):

        prueba = resultado.iloc[i]["Prueba"]

        interpretacion = resultado.iloc[i]["Interpretacion"]

        if interpretacion == "Normalidad":

            print(

                f"✔ {prueba}: Normalidad"
            )

        else:

            print(

                f"❌ {prueba}: No normalidad"
            )

    return resultado


#========================================================
# INDEPENDENCIA DE RESIDUOS
#========================================================

from statsmodels.stats.stattools import durbin_watson

def f_independencia(

        modelo

):

    #----------------------------------------------------
    # Residuos
    #----------------------------------------------------

    residuos = modelo.resid

    #----------------------------------------------------
    # Durbin-Watson
    #----------------------------------------------------

    dw = durbin_watson(

        residuos
    )

    #----------------------------------------------------
    # DataFrame resultado
    #----------------------------------------------------

    resultado = pd.DataFrame({

        "Prueba": [

            "Durbin-Watson"
        ],

        "Estadistico": [

            round(dw,4)
        ],

        "Interpretacion": [

            "Sin autocorrelación"

            if 1.5 <= dw <= 2.5

            else

            "Posible autocorrelación"
        ]
    })

    #----------------------------------------------------
    # Gráfico residuos
    #----------------------------------------------------

    plt.figure(

        figsize = (7,4)
    )

    plt.plot(

        residuos,

        color = "black",

        linewidth = 1
    )

    plt.axhline(

        0,

        linestyle = "--",

        color = "red"
    )

    plt.title(

        "Residuos en secuencia"
    )

    plt.xlabel(

        "Observación"
    )

    plt.ylabel(

        "Residuo"
    )

    plt.show()

    #----------------------------------------------------
    # Resultados
    #----------------------------------------------------

    print("\n============================")

    print("Diagnóstico de Independencia")

    print("============================")

    print(resultado)

    #----------------------------------------------------
    # Interpretación ampliada
    #----------------------------------------------------

    print("\nInterpretación:")

    if 1.5 <= dw <= 2.5:

        print(
            "✔ No existe evidencia "
            "de autocorrelación"
        )

    elif dw < 1.5:

        print(
            "❌ Existe posible "
            "autocorrelación positiva"
        )

    else:

        print(
            "❌ Existe posible "
            "autocorrelación negativa"
        )

    return resultado



#========================================================
# VALIDAR POSTULADOS MULTIMODELO
#========================================================

#========================================================
# VALIDAR POSTULADOS
# OLS + LASSO + RIDGE
#========================================================

def f_validar_postulados_modelos(

        modelos,

        X_datos = None,

        y_datos = None,

        nombres = None,

        redondeo = 4

):

    #----------------------------------------------------
    # Lista modelos
    #----------------------------------------------------

    if not isinstance(modelos, list):

        modelos = [modelos]

    #----------------------------------------------------
    # Nombres
    #----------------------------------------------------

    if nombres is None:

        nombres = [

            f"Modelo_{i+1}"

            for i in range(len(modelos))
        ]

    #----------------------------------------------------
    # Resultados
    #----------------------------------------------------

    resultados = []

    #====================================================
    # RECORRER MODELOS
    #====================================================

    for i, modelo in enumerate(modelos):

        #================================================
        # MODELOS OLS STATSMODELS
        #================================================

        if hasattr(modelo, "model"):

            X = modelo.model.exog

            residuos = modelo.resid

            #--------------------------------------------
            # VIF
            #--------------------------------------------

            vif_valores = []

            for j in range(1, X.shape[1]):

                vif = variance_inflation_factor(

                    X,

                    j
                )

                vif_valores.append(vif)

            vif_max = max(vif_valores)

            #--------------------------------------------
            # Interpretación VIF
            #--------------------------------------------

            if vif_max < 5:

                interpretacion_vif = "Cumple"

            elif vif_max < 10:

                interpretacion_vif = "Moderada"

            else:

                interpretacion_vif = "No cumple"

            #--------------------------------------------
            # Linealidad
            #--------------------------------------------

            reset = linear_reset(

                modelo,

                power = 2,

                use_f = True
            )

            p_lineal = reset.pvalue

            linealidad = (

                "Cumple"

                if p_lineal > 0.05

                else

                "No cumple"
            )

            #--------------------------------------------
            # Homocedasticidad
            #--------------------------------------------

            bp = het_breuschpagan(

                residuos,

                X
            )

            p_homo = bp[1]

            homocedasticidad = (

                "Cumple"

                if p_homo > 0.05

                else

                "No cumple"
            )

        #================================================
        # MODELOS LASSO / RIDGE
        #================================================

        else:

            #--------------------------------------------
            # Validación
            #--------------------------------------------

            if X_datos is None or y_datos is None:

                raise ValueError(

                    "LASSO/RIDGE requieren "
                    "X_datos e y_datos"
                )

            #--------------------------------------------
            # Predicciones
            #--------------------------------------------

            pred = modelo.predict(

                X_datos
            )

            residuos = y_datos - pred

            #--------------------------------------------
            # VIF
            #--------------------------------------------

            vif_valores = []

            for j in range(X_datos.shape[1]):

                vif = variance_inflation_factor(

                    X_datos.values,

                    j
                )

                vif_valores.append(vif)

            vif_max = max(vif_valores)

            #--------------------------------------------
            # Interpretación VIF
            #--------------------------------------------

            if vif_max < 5:

                interpretacion_vif = "Cumple"

            elif vif_max < 10:

                interpretacion_vif = "Moderada"

            else:

                interpretacion_vif = "No cumple"

            #--------------------------------------------
            # No aplica formalmente
            #--------------------------------------------

            linealidad = "NA"

            homocedasticidad = "NA"

        #================================================
        # NORMALIDAD
        #================================================

        shapiro_test = shapiro(

            residuos
        )

        normalidad = (

            "Cumple"

            if shapiro_test.pvalue > 0.05

            else

            "No cumple"
        )

        #================================================
        # INDEPENDENCIA
        #================================================

        dw = durbin_watson(

            residuos
        )

        independencia = (

            "Cumple"

            if 1.5 <= dw <= 2.5

            else

            "No cumple"
        )

        #================================================
        # RESULTADO
        #================================================

        resultados.append({

            "Modelo":

                nombres[i],

            "Multicolinealidad":

                interpretacion_vif,

            "VIF_Max":

                round(vif_max, redondeo),

            "Linealidad":

                linealidad,

            "Homocedasticidad":

                homocedasticidad,

            "Normalidad":

                normalidad,

            "Independencia":

                independencia
        })

    #----------------------------------------------------
    # DataFrame final
    #----------------------------------------------------

    resultados = pd.DataFrame(

        resultados
    )

    #----------------------------------------------------
    # Mostrar
    #----------------------------------------------------

    print("\n============================")

    print("Validación de Postulados")

    print("============================")

    print(resultados)

    return resultados

#========================================================
# ECUACIÓN DEL MODELO
#========================================================

#========================================================
# ECUACIONES DE MODELOS
# OLS + LASSO + RIDGE
#========================================================

def f_ecuaciones_modelos(

        modelos,

        nombres = None,

        redondeo = 4

):

    #----------------------------------------------------
    # Convertir a lista
    #----------------------------------------------------

    if not isinstance(modelos, list):

        modelos = [modelos]

    #----------------------------------------------------
    # Nombres modelos
    #----------------------------------------------------

    if nombres is None:

        nombres = [

            f"Modelo_{i+1}"

            for i in range(len(modelos))
        ]

    #----------------------------------------------------
    # Lista ecuaciones
    #----------------------------------------------------

    ecuaciones = []

    #====================================================
    # RECORRER MODELOS
    #====================================================

    for i, modelo in enumerate(modelos):

        print("\n============================")

        print(

            f"ECUACIÓN: {nombres[i]}"
        )

        print("============================\n")

        #================================================
        # MODELOS OLS (STATSMODELS)
        #================================================

        if hasattr(modelo, "params"):

            coefs = modelo.params.round(

                redondeo
            )

            intercepto = coefs.iloc[0]

            variables = coefs.index[1:]

            valores = coefs.iloc[1:]

        #================================================
        # MODELOS LASSO / RIDGE
        #================================================

        else:

            intercepto = round(

                modelo.intercept_,

                redondeo
            )

            variables = modelo.columnas_entrenamiento

            valores = np.round(

                modelo.coef_,

                redondeo
            )

        #================================================
        # ECUACIÓN
        #================================================

        ecuacion = f"ŷ = {intercepto}"

        #------------------------------------------------
        # Construcción términos
        #------------------------------------------------

        for variable, valor in zip(

                variables,

                valores
        ):

            signo = (

                " + "

                if valor >= 0

                else

                " - "
            )

            termino = (

                f"{signo}"

                f"{abs(valor)}"

                f"*{variable}"
            )

            ecuacion += termino

        #------------------------------------------------
        # Mostrar
        #------------------------------------------------

        print(ecuacion)

        #------------------------------------------------
        # Guardar
        #------------------------------------------------

        ecuaciones.append({

            "Modelo":

                nombres[i],

            "Ecuacion":

                ecuacion
        })

    #----------------------------------------------------
    # DataFrame final
    #----------------------------------------------------

    ecuaciones = pd.DataFrame(

        ecuaciones
    )

    return ecuaciones

#========================================================
# EVALUACIÓN MULTIMODELO
# OLS + LASSO + RIDGE
#========================================================

from sklearn.metrics import (

    mean_squared_error,

    mean_absolute_error,

    r2_score
)

#========================================================
# EVALUACIÓN MULTIMODELO
# OLS + POLINOMIAL + LASSO + RIDGE
#========================================================

from sklearn.metrics import (

    mean_squared_error,

    mean_absolute_error,

    r2_score
)

def f_evaluacion_modelos(

        modelos,

        datos_validacion,

        variable_dependiente,

        nombres = None,

        redondeo = 4

):

    #----------------------------------------------------
    # Convertir a lista
    #----------------------------------------------------

    if not isinstance(modelos, list):

        modelos = [modelos]

    #----------------------------------------------------
    # Nombres modelos
    #----------------------------------------------------

    if nombres is None:

        nombres = [

            f"Modelo_{i+1}"

            for i in range(len(modelos))
        ]

    #----------------------------------------------------
    # Resultados
    #----------------------------------------------------

    resultados = []

    #====================================================
    # DATOS VALIDACIÓN
    #====================================================

    y_real = datos_validacion[

        variable_dependiente
    ]

    X_val = datos_validacion.drop(

        columns = [variable_dependiente]
    )

    #====================================================
    # RECORRER MODELOS
    #====================================================

    for i, modelo in enumerate(modelos):

        #================================================
        # MODELOS OLS / POLINOMIALES
        #================================================

        if hasattr(modelo, "model"):

            #--------------------------------------------
            # MODELO POLINOMIAL
            #--------------------------------------------

            if hasattr(modelo, "poly_transformador"):

                #----------------------------------------
                # Variables originales
                #----------------------------------------

                X_base = X_val[

                    modelo.nombres_originales
                ]

                #----------------------------------------
                # Transformación polinomial
                #----------------------------------------

                X_poly = modelo.poly_transformador.transform(

                    X_base
                )

                #----------------------------------------
                # Nombres polinomiales
                #----------------------------------------

                nombres_poly = (

                    modelo.poly_transformador
                    .get_feature_names_out(

                        modelo.nombres_originales
                    )
                )

                #----------------------------------------
                # DataFrame
                #----------------------------------------

                X_pred = pd.DataFrame(

                    X_poly,

                    columns = nombres_poly,

                    index = X_base.index
                )

            #--------------------------------------------
            # MODELO LINEAL NORMAL
            #--------------------------------------------

            else:

                X_pred = X_val.copy()

            #--------------------------------------------
            # Constante
            #--------------------------------------------

            X_pred = sm.add_constant(

                X_pred,

                has_constant = "add"
            )

            #--------------------------------------------
            # Reordenar columnas
            #--------------------------------------------

            X_pred = X_pred.reindex(

                columns = modelo.model.exog_names,

                fill_value = 0
            )

            #--------------------------------------------
            # Predicciones
            #--------------------------------------------

            pred = modelo.predict(

                X_pred
            )

            p = X_pred.shape[1] - 1

        #================================================
        # MODELOS LASSO / RIDGE
        #================================================

        else:

            #--------------------------------------------
            # Copia directa
            #--------------------------------------------

            X_pred = X_val.copy()

            #--------------------------------------------
            # Reordenar columnas
            #--------------------------------------------

            X_pred = X_pred.reindex(

                columns = modelo.columnas_entrenamiento,

                fill_value = 0
            )

            #--------------------------------------------
            # Predicción
            #--------------------------------------------

            pred = modelo.predict(

                X_pred
            )

            p = X_pred.shape[1]

        #================================================
        # MÉTRICAS
        #================================================

        mse = mean_squared_error(

            y_real,

            pred
        )

        rmse = np.sqrt(mse)

        mae = mean_absolute_error(

            y_real,

            pred
        )

        r2 = r2_score(

            y_real,

            pred
        )

        #================================================
        # R² AJUSTADO
        #================================================

        n = len(y_real)

        r2_adj = 1 - (

            (1 - r2)

            * (n - 1)

            / (n - p - 1)
        )

        #================================================
        # RESULTADOS
        #================================================

        resultados.append({

            "Modelo":

                nombres[i],

            "R_square":

                round(r2, redondeo),

            "R_square_ajustado":

                round(r2_adj, redondeo),

            "MSE":

                round(mse, redondeo),

            "RMSE":

                round(rmse, redondeo),

            "MAE":

                round(mae, redondeo)
        })

    #----------------------------------------------------
    # DataFrame final
    #----------------------------------------------------

    resultados = pd.DataFrame(

        resultados
    )

    #----------------------------------------------------
    # Mostrar
    #----------------------------------------------------

    print("\n============================")

    print("Evaluación de Modelos")

    print("============================")

    print(resultados)

    return resultados

## Cargar datos

Se cargan los datos llamando la función *f_cargar_atos()* y la *url* en donde precisamente está el conjunto de datos de rendimiento académico. https://raw.githubusercontent.com/rpizarrog/Libro-Aprendizaje-Automatico.-Casos-de-Estudio-con-R-y-Python/refs/heads/main/datos/datos%20educacion%20para%20regresiones%20multiple%20polinomiales%20rendimiento_academico.csv .

In [74]:
url = "https://raw.githubusercontent.com/rpizarrog/Libro-Aprendizaje-Automatico.-Casos-de-Estudio-con-R-y-Python/refs/heads/main/datos/datos%20educacion%20para%20regresiones%20multiple%20polinomiales%20rendimiento_academico.csv"
datos = f_cargar_datos(url)

## Visualización de datos

In [75]:
f_visualizar_head_tail_reducido(datos)

,horas_estudio,tiempo_lectura,horas_sueno,uso_redes,...,nivel_socioeconomico,apoyo_familiar,estres,rendimiento_academico
0,9,9,8,6,...,3,8,5,77.96
1,1,1,6,4,...,5,4,1,81.15
2,6,6,9,7,...,2,1,4,84.74
3,4,4,5,6,...,5,8,5,84.77
4,5,5,6,5,...,3,2,2,82.41
5,10,10,5,8,...,5,4,5,79.28
6,...,...,...,...,...,...,...,...,...
7,4,3,5,5,...,4,5,4,82.79
8,4,5,9,3,...,1,7,10,85.53
9,7,6,5,1,...,4,1,4,87.01
10,5,4,5,5,...,4,10,10,87.86
11,6,7,4,7,...,5,5,3,91.4
12,9,9,8,5,...,2,4,2,85.46

## Estadísticos descriptivos

In [76]:
f_describir_datos(datos)

{'describe':        horas_estudio  tiempo_lectura  horas_sueno    uso_redes   motivacion  \
 count    6000.000000     6000.000000  6000.000000  6000.000000  6000.000000
 mean        5.503667        5.520667     6.485667     4.540500     5.455500
 std         2.908332        2.915703     1.701453     2.296281     2.887457
 min         1.000000        1.000000     4.000000     1.000000     1.000000
 25%         3.000000        3.000000     5.000000     3.000000     3.000000
 50%         5.000000        6.000000     7.000000     5.000000     5.000000
 75%         8.000000        8.000000     8.000000     7.000000     8.000000
 max        10.000000       10.000000     9.000000     8.000000    10.000000

         asistencia  nivel_socioeconomico  apoyo_familiar       estres  \
 count  6000.000000           6000.000000     6000.000000  6000.000000
 mean     80.018333              2.990667        5.603333     5.496000
 std      11.786736              1.427207        2.851843     2.860539
 min      60.000000              1.000000        1.000000     1.000000
 25%      70.000000              2.000000        3.000000     3.000000
 50%      80.000000              3.000000        6.000000     5.000000
 75%      90.000000              4.000000        8.000000     8.000000
 max     100.000000              5.000000       10.000000    10.000000

        rendimiento_academico
 count            6000.000000
 mean               83.000538
 std                 5.255007
 min                70.000000
 25%                78.937500
 50%                82.650000
 75%                86.700000
 max               100.000000  ,
 'structure': horas_estudio              int64
 tiempo_lectura             int64
 horas_sueno                int64
 uso_redes                  int64
 motivacion                 int64
 asistencia                 int64
 nivel_socioeconomico       int64
 apoyo_familiar             int64
 estres                     int64
 rendimiento_academico    float64
 dtype: object}

# Desarrollo

## Partición de datos

Se generan los dos conjuntos de datos, *70%* para datos de entrenamiento y *30%* para datos de validación los cuales se usarán para crear y evaluar modelos de regesión lineal múltiple y polinomial múltiples de grado dos y tres.

In [77]:
particion = f_particionar_datos(datos)

datos_entrenamiento = particion["datos_entrenamiento"]
datos_validacion = particion["datos_validacion"]

f_visualizar_head_tail_reducido(datos_entrenamiento)

,horas_estudio,tiempo_lectura,horas_sueno,uso_redes,...,nivel_socioeconomico,apoyo_familiar,estres,rendimiento_academico
0,6,5,8,1,...,5,7,6,79.38
1,7,9,5,7,...,1,5,3,78.11
2,4,4,7,4,...,2,4,10,81.49
3,7,9,9,5,...,3,7,2,86.71
4,5,5,7,2,...,5,2,5,82.72
5,5,5,5,6,...,1,7,2,79.95
6,...,...,...,...,...,...,...,...,...
7,1,1,8,5,...,3,3,10,77.26
8,7,7,7,7,...,3,4,9,81.81
9,2,5,5,4,...,1,10,4,83.48
10,6,5,5,1,...,4,7,1,83.53
11,10,10,4,6,...,5,8,1,85.04
12,9,8,6,5,...,5,2,9,84.7

Datos de validación:

In [78]:
f_visualizar_head_tail_reducido(datos_validacion)

,horas_estudio,tiempo_lectura,horas_sueno,uso_redes,...,nivel_socioeconomico,apoyo_familiar,estres,rendimiento_academico
0,6,5,5,3,...,4,1,9,81.82
1,9,8,5,6,...,2,8,8,93.28
2,4,2,8,2,...,5,1,1,79.05
3,1,1,4,3,...,4,8,2,77.69
4,8,8,6,4,...,5,7,5,76.26
5,5,6,8,5,...,3,10,1,84.59
6,...,...,...,...,...,...,...,...,...
7,4,4,6,2,...,4,7,2,81.73
8,1,1,8,3,...,4,9,7,81.64
9,9,9,6,3,...,2,5,9,88.67
10,8,9,7,6,...,2,5,5,87.94
11,5,5,5,3,...,1,6,7,80.3
12,5,4,6,7,...,1,2,6,76.6

### Crear modelo de regresión lineal múltiple

Se manda llamar la función *f_construir_modelo_RLM_statsmodels()* con los datos de entrenamiento y la variable dependiente con la cual se construye el modelo de regresión lineal mútiple.

In [79]:
modelo_RLM = f_construir_modelo_RLM_statsmodels(datos_entrenamiento, "rendimiento_academico")

                              OLS Regression Results
=================================================================================
Dep. Variable:     rendimiento_academico   R-squared:                       0.887
Model:                               OLS   Adj. R-squared:                  0.886
Method:                    Least Squares   F-statistic:                     3639.
Date:                   Wed, 20 May 2026   Prob (F-statistic):               0.00
Time:                           21:14:50   Log-Likelihood:                -8343.6
No. Observations:                   4200   AIC:                         1.671e+04
Df Residuals:                       4190   BIC:                         1.677e+04
Df Model:                              9
Covariance Type:               nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   61.2417      0.251    244.198      0.000      60.750      61.733
horas_estudio            0.3645      0.028     12.826      0.000       0.309       0.420
tiempo_lectura           0.1792      0.028      6.326      0.000       0.124       0.235
horas_sueno             -0.1031      0.016     -6.468      0.000      -0.134      -0.072
uso_redes                0.5677      0.012     47.757      0.000       0.544       0.591
motivacion               1.4517      0.009    153.280      0.000       1.433       1.470
asistencia               0.0367      0.002     15.869      0.000       0.032       0.041
nivel_socioeconomico     0.5548      0.019     28.859      0.000       0.517       0.592
apoyo_familiar           0.3429      0.010     35.769      0.000       0.324       0.362
estres                   0.4373      0.010     45.844      0.000       0.419       0.456
==============================================================================
Omnibus:                      326.924   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              405.400
Skew:                          -0.747   Prob(JB):                     9.30e-89
Kurtosis:                       3.296   Cond. No.                         759.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### Postulados del modelo de regesión lineal múltiple

El conjunto de datos y específicamente las variables independientes, presentan de manera moderada multicolinealidad entre ellas, además, el modleo no cumple con los postulados de linealidad ni normalidad en los resiudos.

In [80]:
f_validar_postulados_modelos (modelo_RLM)

============================
Validación de Postulados
============================
     Modelo Multicolinealidad  VIF_Max Linealidad Homocedasticidad Normalidad  \
0  Modelo_1          Moderada   9.1437  No cumple           Cumple  No cumple

  Independencia
0        Cumple

,Modelo,Multicolinealidad,VIF_Max,Linealidad,Homocedasticidad,Normalidad,Independencia
0,Modelo_1,Moderada,9.1437,No cumple,Cumple,No cumple,Cumple

### Crear modelo de regresión polinomial de segundo orden

In [81]:
modelo_RPM_2 = f_multiple_polinomial(datos_entrenamiento, "rendimiento_academico", 2)

============================
MODELO POLINOMIAL GRADO 2
============================
Número de variables originales: 9
Número de términos polinomiales: 54
                              OLS Regression Results
=================================================================================
Dep. Variable:     rendimiento_academico   R-squared:                       0.996
Model:                               OLS   Adj. R-squared:                  0.995
Method:                    Least Squares   F-statistic:                 1.700e+04
Date:                   Wed, 20 May 2026   Prob (F-statistic):               0.00
Time:                           21:14:50   Log-Likelihood:                -1564.2
No. Observations:                   4200   AIC:                             3238.
Df Residuals:                       4145   BIC:                             3587.
Df Model:                             54
Covariance Type:               nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
const                                  63.7353      0.402    158.616      0.000      62.948      64.523
horas_estudio                           1.3340      0.052     25.622      0.000       1.232       1.436
tiempo_lectura                          0.0776      0.052      1.496      0.135      -0.024       0.179
horas_sueno                             0.3855      0.039      9.888      0.000       0.309       0.462
uso_redes                              -0.2319      0.024     -9.578      0.000      -0.279      -0.184
motivacion                              0.6912      0.019     36.326      0.000       0.654       0.728
asistencia                              0.0471      0.008      6.168      0.000       0.032       0.062
nivel_socioeconomico                    0.5446      0.040     13.676      0.000       0.466       0.623
apoyo_familiar                          0.3341      0.019     17.160      0.000       0.296       0.372
estres                                 -0.5091      0.019    -26.836      0.000      -0.546      -0.472
horas_estudio^2                        -0.1515      0.004    -37.213      0.000      -0.159      -0.144
horas_estudio tiempo_lectura           -0.0074      0.008     -0.984      0.325      -0.022       0.007
horas_estudio horas_sueno               0.0007      0.003      0.196      0.844      -0.006       0.007
horas_estudio uso_redes                 0.0012      0.002      0.496      0.620      -0.004       0.006
horas_estudio motivacion                0.1377      0.002     69.840      0.000       0.134       0.142
horas_estudio asistencia             6.225e-05      0.000      0.129      0.898      -0.001       0.001
horas_estudio nivel_socioeconomico      0.0050      0.004      1.227      0.220      -0.003       0.013
horas_estudio apoyo_familiar            0.0012      0.002      0.611      0.541      -0.003       0.005
horas_estudio estres                   -0.0005      0.002     -0.242      0.809      -0.005       0.004
tiempo_lectura^2                        0.0117      0.004      2.919      0.004       0.004       0.020
tiempo_lectura horas_sueno              0.0004      0.003      0.130      0.896      -0.006       0.007
tiempo_lectura uso_redes            -1.493e-05      0.002     -0.006      0.995      -0.005       0.005
tiempo_lectura motivacion              -0.0007      0.002     -0.361      0.718      -0.005       0.003
tiempo_lectura asistencia            7.622e-05      0.000      0.158      0.874      -0.001       0.001
tiempo_lectura nivel_socioeconomico    -0.0048      0.004     -1.192      0.233      -0.013       0.003
tiempo_lectura apoyo_familiar          -0.0015      0.002     -0.752      0.452      -0.005       0.002
tiempo_lectura estres                   0.0005      0.002      0.261      0.794      -0.003       0.005
horas_sueno^2                          -0.0341      0.002    -15.462      0.000      -0.038      -0.030
horas_sueno uso_redes                  -0.0004      0.001     -0.304      0.761      -0.003       0.002
horas_sueno motivacion                 -0.0004      0.001     -0.338      0.736      -0.003       0.002
horas_sueno asistencia                 -0.0006      0.000     -2.125      0.034      -0.001   -4.47e-05
horas_sueno nivel_socioeconomico       -0.0013      0.002     -0.563      0.573      -0.006       0.003
horas_sueno apoyo_familiar              0.0002      0.001      0.207      0.836      -0.002       0.002
horas_sueno estres                      0.0001      0.001      0.103      0.918      -0.002       0.002
uso_redes^2                             0.0900      0.001     75.006      0.000       0.088       0.092
uso_redes motivacion                   -0.0006      0.001     -0.688      0.491      -0.002       0.001
uso_redes asistencia                   -0.0001      0.000     -0.695      0.487      -0.001       0.000
uso_redes nivel_socioeconomico          0.0010      0.002      0.619      0.536      -0.002       0.004
uso_redes apoyo_familiar                0.0017      0.001      1.973      0.049    1.08e-05       0.003
uso_redes estres                       -0.0022      0.001     -2.557      0.011      -0.004      -0.001
motivacion^2                           -0.0004      0.001     -0.593      0.553      -0.002       0.001
motivacion asistencia                7.447e-05      0.000      0.462      0.644      -0.000       0.000
motivacion nivel_socioeconomico     -1.592e-05      0.001     -0.012      0.991      -0.003       0.003
motivacion apoyo_familiar               0.0011      0.001      1.575      0.115      -0.000       0.002
motivacion estres                      -0.0014      0.001     -2.104      0.035      -0.003   -9.65e-05
asistencia^2                        -5.283e-05   4.42e-05     -1.195      0.232      -0.000    3.38e-05
asistencia nivel_socioeconomico        -0.0005      0.000     -1.466      0.143      -0.001       0.000
asistencia apoyo_familiar           -6.151e-05      0.000     -0.373      0.709      -0.000       0.000
asistencia estres                       0.0001      0.000      0.845      0.398      -0.000       0.000
nivel_socioeconomico^2                  0.0010      0.003      0.302      0.762      -0.005       0.007
nivel_socioeconomico apoyo_familiar    -0.0010      0.001     -0.738      0.460      -0.004       0.002
nivel_socioeconomico estres             0.0015      0.001      1.132      0.258      -0.001       0.004
apoyo_familiar^2                        0.0003      0.001      0.419      0.675      -0.001       0.002
apoyo_familiar estres                  -0.0003      0.001     -0.404      0.686      -0.002       0.001
estres^2                                0.0854      0.001    112.996      0.000       0.084       0.087
==============================================================================
Omnibus:                        0.645   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.724   Jarque-Bera (JB):                0.691
Skew:                           0.009   Prob(JB):                        0.708
Kurtosis:                       2.940   Cond. No.                     5.12e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

### Crear modelo de regresión polinomial de tercer orden

Dada la complejidad de la cosntruccón del modelos polinomial múltiple de tercer orden el tiempo es un factor importante a considerar, en el equipo en donde fue ejecutado la función

In [82]:
modelo_RPM_3 = f_multiple_polinomial(datos_entrenamiento, "rendimiento_academico", 3)

============================
MODELO POLINOMIAL GRADO 3
============================
Número de variables originales: 9
Número de términos polinomiales: 219
                              OLS Regression Results
=================================================================================
Dep. Variable:     rendimiento_academico   R-squared:                       0.996
Model:                               OLS   Adj. R-squared:                  0.996
Method:                    Least Squares   F-statistic:                     4490.
Date:                   Wed, 20 May 2026   Prob (F-statistic):               0.00
Time:                           21:14:50   Log-Likelihood:                -1335.5
No. Observations:                   4200   AIC:                             3111.
Df Residuals:                       3980   BIC:                             4506.
Df Model:                            219
Covariance Type:               nonrobust
======================================================================================================================
                                                         coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
const                                                 60.4377      3.062     19.738      0.000      54.435      66.441
horas_estudio                                          2.0914      0.425      4.925      0.000       1.259       2.924
tiempo_lectura                                        -0.3330      0.420     -0.793      0.428      -1.156       0.490
horas_sueno                                           -0.1974      0.368     -0.537      0.591      -0.918       0.523
uso_redes                                             -0.4150      0.197     -2.108      0.035      -0.801      -0.029
motivacion                                             0.8538      0.155      5.501      0.000       0.550       1.158
asistencia                                             0.1820      0.093      1.956      0.051      -0.000       0.365
nivel_socioeconomico                                   0.8366      0.335      2.501      0.012       0.181       1.492
apoyo_familiar                                         0.2523      0.159      1.588      0.112      -0.059       0.564
estres                                                -0.4393      0.153     -2.871      0.004      -0.739      -0.139
horas_estudio^2                                       -0.1429      0.038     -3.784      0.000      -0.217      -0.069
horas_estudio tiempo_lectura                          -0.0204      0.070     -0.293      0.770      -0.157       0.116
horas_estudio horas_sueno                             -0.0493      0.039     -1.259      0.208      -0.126       0.027
horas_estudio uso_redes                               -0.0600      0.025     -2.435      0.015      -0.108      -0.012
horas_estudio motivacion                               0.1241      0.020      6.197      0.000       0.085       0.163
horas_estudio asistencia                              -0.0087      0.008     -1.093      0.274      -0.024       0.007
horas_estudio nivel_socioeconomico                    -0.0220      0.042     -0.526      0.599      -0.104       0.060
horas_estudio apoyo_familiar                           0.0052      0.020      0.255      0.799      -0.035       0.045
horas_estudio estres                                  -0.0336      0.020     -1.650      0.099      -0.073       0.006
tiempo_lectura^2                                      -0.0316      0.038     -0.837      0.403      -0.106       0.042
tiempo_lectura horas_sueno                             0.0797      0.039      2.025      0.043       0.003       0.157
tiempo_lectura uso_redes                               0.0523      0.025      2.123      0.034       0.004       0.101
tiempo_lectura motivacion                              0.0050      0.020      0.252      0.801      -0.034       0.044
tiempo_lectura asistencia                              0.0054      0.008      0.688      0.492      -0.010       0.021
tiempo_lectura nivel_socioeconomico                    0.0050      0.042      0.119      0.905      -0.077       0.087
tiempo_lectura apoyo_familiar                         -0.0033      0.020     -0.163      0.871      -0.043       0.037
tiempo_lectura estres                                  0.0237      0.020      1.172      0.241      -0.016       0.063
horas_sueno^2                                          0.0437      0.037      1.184      0.236      -0.029       0.116
horas_sueno uso_redes                                 -0.0033      0.018     -0.182      0.855      -0.039       0.032
horas_sueno motivacion                                -0.0384      0.014     -2.703      0.007      -0.066      -0.011
horas_sueno asistencia                                -0.0005      0.005     -0.105      0.916      -0.010       0.009
horas_sueno nivel_socioeconomico                       0.0261      0.029      0.896      0.370      -0.031       0.083
horas_sueno apoyo_familiar                             0.0130      0.014      0.907      0.364      -0.015       0.041
horas_sueno estres                                     0.0141      0.014      1.001      0.317      -0.014       0.042
uso_redes^2                                            0.1942      0.014     14.313      0.000       0.168       0.221
uso_redes motivacion                                  -0.0167      0.009     -1.862      0.063      -0.034       0.001
uso_redes asistencia                                  -0.0024      0.003     -0.708      0.479      -0.009       0.004
uso_redes nivel_socioeconomico                        -0.0292      0.019     -1.575      0.115      -0.066       0.007
uso_redes apoyo_familiar                               0.0120      0.009      1.322      0.186      -0.006       0.030
uso_redes estres                                      -0.0128      0.009     -1.443      0.149      -0.030       0.005
motivacion^2                                           0.0014      0.008      0.174      0.862      -0.015       0.018
motivacion asistencia                                 -0.0004      0.003     -0.132      0.895      -0.006       0.005
motivacion nivel_socioeconomico                        0.0071      0.015      0.480      0.631      -0.022       0.036
motivacion apoyo_familiar                              0.0128      0.007      1.751      0.080      -0.002       0.027
motivacion estres                                     -0.0033      0.007     -0.461      0.645      -0.017       0.011
asistencia^2                                          -0.0014      0.001     -1.309      0.191      -0.003       0.001
asistencia nivel_socioeconomico                       -0.0086      0.006     -1.510      0.131      -0.020       0.003
asistencia apoyo_familiar                              0.0007      0.003      0.262      0.793      -0.005       0.006
asistencia estres                                     -0.0019      0.003     -0.699      0.485      -0.007       0.003
nivel_socioeconomico^2                                -0.0005      0.041     -0.012      0.990      -0.080       0.079
nivel_socioeconomico apoyo_familiar                   -0.0047      0.015     -0.308      0.758      -0.035       0.025
nivel_socioeconomico estres                            0.0185      0.015      1.270      0.204      -0.010       0.047
apoyo_familiar^2                                      -0.0082      0.009     -0.963      0.335      -0.025       0.009
apoyo_familiar estres                                  0.0044      0.007      0.605      0.545      -0.010       0.018
estres^2                                               0.0801      0.008      9.589      0.000       0.064       0.097
horas_estudio^3                                        0.0047      0.003      1.841      0.066      -0.000       0.010
horas_estudio^2 tiempo_lectura                        -0.0094      0.007     -1.389      0.165      -0.023       0.004
horas_estudio^2 horas_sueno                           -0.0003      0.002     -0.148      0.882      -0.005       0.004
horas_estudio^2 uso_redes                             -0.0004      0.002     -0.236      0.813      -0.004       0.003
horas_estudio^2 motivacion                            -0.0007      0.001     -0.530      0.596      -0.003       0.002
horas_estudio^2 asistencia                         -3.779e-05      0.000     -0.109      0.913      -0.001       0.001
horas_estudio^2 nivel_socioeconomico                  -0.0029      0.003     -0.990      0.322      -0.009       0.003
horas_estudio^2 apoyo_familiar                        -0.0016      0.001     -1.055      0.292      -0.004       0.001
horas_estudio^2 estres                                -0.0010      0.002     -0.651      0.515      -0.004       0.002
horas_estudio tiempo_lectura^2                         0.0047      0.007      0.709      0.478      -0.008       0.018
horas_estudio tiempo_lectura horas_sueno            7.504e-05      0.004      0.017      0.986      -0.009       0.009
horas_estudio tiempo_lectura uso_redes                 0.0011      0.003      0.325      0.745      -0.005       0.007
horas_estudio tiempo_lectura motivacion               -0.0004      0.003     -0.142      0.887      -0.006       0.005
horas_estudio tiempo_lectura asistencia                0.0002      0.001      0.287      0.774      -0.001       0.001
horas_estudio tiempo_lectura nivel_socioeconomico      0.0066      0.005      1.224      0.221      -0.004       0.017
horas_estudio tiempo_lectura apoyo_familiar            0.0020      0.003      0.719      0.472      -0.003       0.007
horas_estudio tiempo_lectura estres                    0.0029      0.003      0.993      0.321      -0.003       0.009
horas_estudio horas_sueno^2                            0.0026      0.002      1.150      0.250      -0.002       0.007
horas_estudio horas_sueno uso_redes                    0.0013      0.001      0.900      0.368      -0.002       0.004
horas_estudio horas_sueno motivacion                   0.0010      0.001      0.832      0.405      -0.001       0.003
horas_estudio horas_sueno asistencia                   0.0001      0.000      0.412      0.680      -0.000       0.001
horas_estudio horas_sueno nivel_socioeconomico        -0.0024      0.002     -1.024      0.306      -0.007       0.002
horas_estudio horas_sueno apoyo_familiar              -0.0003      0.001     -0.238      0.812      -0.003       0.002
horas_estudio horas_sueno estres                       0.0016      0.001      1.297      0.195      -0.001       0.004
horas_estudio uso_redes^2                              0.0018      0.001      1.432      0.152      -0.001       0.004
horas_estudio uso_redes motivacion                     0.0014      0.001      1.601      0.109      -0.000       0.003
horas_estudio uso_redes asistencia                     0.0003      0.000      1.202      0.230      -0.000       0.001
horas_estudio uso_redes nivel_socioeconomico           0.0026      0.002      1.499      0.134      -0.001       0.006
horas_estudio uso_redes apoyo_familiar                -0.0007      0.001     -0.757      0.449      -0.002       0.001
horas_estudio uso_redes estres                         0.0008      0.001      0.912      0.362      -0.001       0.003
horas_estudio motivacion^2                             0.0009      0.001      1.162      0.245      -0.001       0.002
horas_estudio motivacion asistencia                 2.531e-05      0.000      0.151      0.880      -0.000       0.000
horas_estudio motivacion nivel_socioeconomico          0.0029      0.001      2.034      0.042       0.000       0.006
horas_estudio motivacion apoyo_familiar               -0.0011      0.001     -1.517      0.129      -0.002       0.000
horas_estudio motivacion estres                       -0.0005      0.001     -0.763      0.446      -0.002       0.001
horas_estudio asistencia^2                          2.777e-05   4.58e-05      0.606      0.545   -6.21e-05       0.000
horas_estudio asistencia nivel_socioeconomico         -0.0002      0.000     -0.516      0.606      -0.001       0.001
horas_estudio asistencia apoyo_familiar                0.0003      0.000      1.759      0.079    -3.5e-05       0.001
horas_estudio asistencia estres                     7.893e-05      0.000      0.443      0.657      -0.000       0.000
horas_estudio nivel_socioeconomico^2                   0.0041      0.003      1.197      0.231      -0.003       0.011
horas_estudio nivel_socioeconomico apoyo_familiar     -0.0009      0.001     -0.623      0.533      -0.004       0.002
horas_estudio nivel_socioeconomico estres              0.0015      0.001      1.014      0.310      -0.001       0.004
horas_estudio apoyo_familiar^2                        -0.0011      0.001     -1.367      0.172      -0.003       0.000
horas_estudio apoyo_familiar estres                    0.0005      0.001      0.666      0.505      -0.001       0.002
horas_estudio estres^2                                 0.0002      0.001      0.295      0.768      -0.001       0.002
tiempo_lectura^3                                       0.0032      0.002      1.330      0.183      -0.002       0.008
tiempo_lectura^2 horas_sueno                          -0.0005      0.002     -0.206      0.837      -0.005       0.004
tiempo_lectura^2 uso_redes                            -0.0009      0.002     -0.493      0.622      -0.004       0.003
tiempo_lectura^2 motivacion                            0.0007      0.001      0.495      0.620      -0.002       0.003
tiempo_lectura^2 asistencia                           -0.0001      0.000     -0.379      0.705      -0.001       0.001
tiempo_lectura^2 nivel_socioeconomico                 -0.0036      0.003     -1.253      0.210      -0.009       0.002
tiempo_lectura^2 apoyo_familiar                       -0.0005      0.001     -0.347      0.728      -0.003       0.002
tiempo_lectura^2 estres                               -0.0017      0.002     -1.089      0.276      -0.005       0.001
tiempo_lectura horas_sueno^2                          -0.0038      0.002     -1.668      0.095      -0.008       0.001
tiempo_lectura horas_sueno uso_redes                  -0.0014      0.001     -0.997      0.319      -0.004       0.001
tiempo_lectura horas_sueno motivacion                 -0.0013      0.001     -1.127      0.260      -0.004       0.001
tiempo_lectura horas_sueno asistencia                 -0.0001      0.000     -0.478      0.633      -0.001       0.000
tiempo_lectura horas_sueno nivel_socioeconomico        0.0011      0.002      0.479      0.632      -0.003       0.006
tiempo_lectura horas_sueno apoyo_familiar              0.0002      0.001      0.198      0.843      -0.002       0.003
tiempo_lectura horas_sueno estres                     -0.0011      0.001     -0.934      0.351      -0.004       0.001
tiempo_lectura uso_redes^2                            -0.0014      0.001     -1.128      0.260      -0.004       0.001
tiempo_lectura uso_redes motivacion                   -0.0009      0.001     -1.025      0.305      -0.003       0.001
tiempo_lectura uso_redes asistencia                   -0.0002      0.000     -1.160      0.246      -0.001       0.000
tiempo_lectura uso_redes nivel_socioeconomico         -0.0020      0.002     -1.162      0.245      -0.005       0.001
tiempo_lectura uso_redes apoyo_familiar                0.0008      0.001      0.953      0.340      -0.001       0.003
tiempo_lectura uso_redes estres                       -0.0004      0.001     -0.434      0.664      -0.002       0.001
tiempo_lectura motivacion^2                           -0.0006      0.001     -0.771      0.441      -0.002       0.001
tiempo_lectura motivacion asistencia                 6.57e-05      0.000      0.391      0.696      -0.000       0.000
tiempo_lectura motivacion nivel_socioeconomico        -0.0022      0.001     -1.570      0.117      -0.005       0.001
tiempo_lectura motivacion apoyo_familiar               0.0011      0.001      1.621      0.105      -0.000       0.003
tiempo_lectura motivacion estres                       0.0005      0.001      0.682      0.495      -0.001       0.002
tiempo_lectura asistencia^2                        -1.564e-05   4.58e-05     -0.342      0.733      -0.000    7.41e-05
tiempo_lectura asistencia nivel_socioeconomico         0.0004      0.000      1.072      0.284      -0.000       0.001
tiempo_lectura asistencia apoyo_familiar              -0.0003      0.000     -1.698      0.090      -0.001    4.54e-05
tiempo_lectura asistencia estres                   -6.265e-05      0.000     -0.354      0.724      -0.000       0.000
tiempo_lectura nivel_socioeconomico^2                 -0.0046      0.003     -1.357      0.175      -0.011       0.002
tiempo_lectura nivel_socioeconomico apoyo_familiar     0.0013      0.001      0.890      0.373      -0.002       0.004
tiempo_lectura nivel_socioeconomico estres            -0.0009      0.001     -0.602      0.547      -0.004       0.002
tiempo_lectura apoyo_familiar^2                        0.0007      0.001      0.811      0.418      -0.001       0.002
tiempo_lectura apoyo_familiar estres                  -0.0003      0.001     -0.465      0.642      -0.002       0.001
tiempo_lectura estres^2                               -0.0003      0.001     -0.419      0.675      -0.002       0.001
horas_sueno^3                                         -0.0029      0.002     -1.786      0.074      -0.006       0.000
horas_sueno^2 uso_redes                               -0.0002      0.001     -0.212      0.832      -0.002       0.002
horas_sueno^2 motivacion                               0.0008      0.001      0.990      0.322      -0.001       0.002
horas_sueno^2 asistencia                              -0.0002      0.000     -0.947      0.343      -0.001       0.000
horas_sueno^2 nivel_socioeconomico                    -0.0007      0.002     -0.467      0.640      -0.004       0.002
horas_sueno^2 apoyo_familiar                          -0.0005      0.001     -0.591      0.555      -0.002       0.001
horas_sueno^2 estres                                   0.0004      0.001      0.472      0.637      -0.001       0.002
horas_sueno uso_redes^2                               -0.0002      0.001     -0.290      0.772      -0.002       0.001
horas_sueno uso_redes motivacion                       0.0011      0.000      2.190      0.029       0.000       0.002
horas_sueno uso_redes asistencia                    1.574e-05      0.000      0.134      0.893      -0.000       0.000
horas_sueno uso_redes nivel_socioeconomico            -0.0010      0.001     -1.078      0.281      -0.003       0.001
horas_sueno uso_redes apoyo_familiar                   0.0003      0.000      0.635      0.526      -0.001       0.001
horas_sueno uso_redes estres                           0.0004      0.000      0.830      0.407      -0.001       0.001
horas_sueno motivacion^2                               0.0007      0.000      1.669      0.095      -0.000       0.002
horas_sueno motivacion asistencia                      0.0002    9.4e-05      2.257      0.024    2.78e-05       0.000
horas_sueno motivacion nivel_socioeconomico           -0.0001      0.001     -0.163      0.871      -0.002       0.001
horas_sueno motivacion apoyo_familiar                  0.0003      0.000      0.871      0.384      -0.000       0.001
horas_sueno motivacion estres                         -0.0002      0.000     -0.403      0.687      -0.001       0.001
horas_sueno asistencia^2                            1.939e-05   2.59e-05      0.748      0.454   -3.14e-05    7.02e-05
horas_sueno asistencia nivel_socioeconomico        -4.159e-05      0.000     -0.217      0.828      -0.000       0.000
horas_sueno asistencia apoyo_familiar                 -0.0001   9.65e-05     -1.167      0.243      -0.000    7.66e-05

### Validar modelos

Se validan los tres modelos ejecutando la función f_validar_postulados_modelos() con los argumentos adecuados: la lista de los modelos, las variables independientes y la variable dependiente así como los nombres de cada modelo, la salida en modo consola.

  
En los resultados, se identifica que ningún modelo resuelve el problema de multicolinealidad, sin embargo, los modelos polinomiales garantizan validez en los postulados de linealidad, homocedasticidad, normalidad e independencia de residuos en comparación con el modelo de regresión lineal múltiple.

Aquí es importante hacer notar que el tiempo para la validación de todos lo postulados resultó algo considerable aproximadamente 98 segundos tal vez minuto y medio en el equipo personal del autor, una laptop con procesador 12th Gen Intel(R) Core(TM) i9-12950HX (2.30 GHz), 32.0 GB (31.7 GB usable) y tarjeta gráfica NVIDIA RTX A3000 12GB Laptop GPU (12 GB) Intel(R) UHD Graphics (128 MB).

Con lo anterior, será una decisión del lector, validar postulado por postulado como se realizó y describió con los anteriores casos de estudio, finalmente ya se tienen las funciones para validar de manera independiente estos postulados y que se encuentran en la dirección url al principio del caso citada.

In [ ]:
import time
# INICIO
inicio = time.time()
X = datos_entrenamiento.drop(columns = ["rendimiento_academico"]) # Variables independientes

y = datos_entrenamiento["rendimiento_academico"] # Variable dependiente

f_validar_postulados_modelos ([modelo_RLM, modelo_RPM_2, modelo_RPM_3],
                              X,
                              y,
                              nombres = ["RLM Original","Polinomial Múltiple 2","Polinomial Múltiple 3"])
fin = time.time()
tiempo = fin - inicio

print(

    f"\nTiempo de validación de postulados: "
    f"{round(tiempo,4)} segundos"
)

### Evaluar modelos

Se ejecuta la función *f_evaluacion_modelos()* la cual devuelve la evaluación de los estadísticos que permiten valorar la calidad predictiva de los modelos.

Se observa que los modelos polinomiales ofrecen mejor calidad predictiva en comparación con el modelo de regresión lineal múltiple con este conjunto de datos de validación.

In [ ]:
# INICIO
inicio = time.time()
f_evaluacion_modelos([modelo_RLM, modelo_RPM_2, modelo_RPM_2],
    datos_validacion,
    "rendimiento_academico",
    nombres = ["Lineal Múltiple", "Poli Múltiple 2", "Poli Múltiple 2"]
)
fin = time.time()
tiempo = fin - inicio

print(

    f"\nTiempo de ejecución: "
    f"{round(tiempo,4)} segundos"
)

## Construir modelos con datos normalizados

Para disminuir y regular la deficiencia de la multicolinealidad se construyen modelos con datos estandarizados, primero modelos de regresión lineal múltiple, luego, los modelos Lasso y Ridge, estos últimos con la finalidad de ser la alternativa para penalizar y regular la deficiencia de la muticolinealidad en las variables independientes.

Estos modelos se construyen con datos normalizados.

### Normalizar datos

Ahora se manda llamar la función f_ para normalziar los datos originales con los cuales se crean los nuevos datos de entrenamiento y validación para contruir los modelos regresión múltiple, *Lasso* y *Ridge*.

In [ ]:
datos_estandarizados_escalados = f_estandarizar_escalar(datos)
datos_estandarizados = datos_estandarizados_escalados['datos_estandarizados']
# datos_escalados = datos_estandarizados_escalados['datos_escalados']

particion = f_particionar_datos(datos_estandarizados) # Particionar con datos estandarizados

datos_entrenamiento = particion["datos_entrenamiento"]
datos_validacion = particion["datos_validacion"]

f_visualizar_head_tail_reducido(datos_entrenamiento)

In [ ]:
f_visualizar_head_tail_reducido(datos_validacion)

### Modelo de regresión lineal múltiple con datos normalizados

In [ ]:
modelo_RLM_norm = f_construir_modelo_RLM_statsmodels(datos_entrenamiento, "rendimiento_academico")

### Modelo Lasso

In [ ]:
modelo_lasso = f_construir_modelo_lasso(datos_entrenamiento, "rendimiento_academico")

### Modelo Ridge

In [ ]:
modelo_ridge = f_construir_modelo_ridge(datos_entrenamiento, "rendimiento_academico")

### Validación de modelos

In [ ]:
X = datos_entrenamiento.drop(columns = ["rendimiento_academico"]) # Variables independientes

y = datos_entrenamiento["rendimiento_academico"] # Variable dependiente

f_validar_postulados_modelos ([modelo_RLM_norm, modelo_lasso, modelo_ridge],
                              X, y,
                              nombres = ["RLM Normalizado","Lasso","Ridge"])

### Evaluación de modelos

In [ ]:
f_evaluacion_modelos([modelo_RLM_norm, modelo_lasso, modelo_ridge],
    datos_validacion,
    "rendimiento_academico",
    nombres = ["RLM", "LASSO", "RIDGE"]
)

# Interpretación del caso de estudio

El caso tuvo la finalidad de crear, evaluar y comparar modelos de regresión lineal múltiple con modelos de regresión polinomial múltiple de segundo y tercer grado. Se cumple con el objetivo del caso inicialmente definido.

Con datos originales se crearon particiones del 70% para datos de entrenamiento y 30% para datos de validación; se crearon tres modelos: de regresión lineal múltiple polinomiales múltiples de segundo y tercer orden.

El modelo de regresión múltiple con datos originales presenta de manera moderada el postulado de multicolinealidad y no favores al postulado de linealidad y normalidad; sin embargo, si ofrece calidad predictiva alrededor del 88% en el estadístico r square ajustado. Los modelos polinomiales también adolecen del postulado de multicolinealidad, pero garantizan validez en los demás postulados y ofrecen mejor calidad predictiva con alrededor del 99% en el estadístico; sin embargo, si ofrece calidad predictiva alrededor del 88% en el estadístico r square ajustado.

Luego, se transformaron los datos originales a datos estandarizados; con estos datos estandarizados de rendimiento académico, se crearon modelo de regresión lineal múltiple y modelos regularizados Lasso y Ridge.

Los resultados son similares en los estadísticos de evaluación sin embargo la idea de los modelos regularizados es que ayudan a una mejor estabilidad en los coeficientes penalizando los coeficientes dada la multicolinealidad de las variables.

Los resultados son similares a los que se tienen en el caso de estudio con programación *R* y finalmente cumplen con la métrica inicialmente establecida de que los modelos son satisfactorios si tiene un valor de r square ajustado por encima del *85%*.